name: tests

on: [push]

defaults:
  run:
    shell: bash -l {0}


jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]
        os: ['ubuntu', 'macos']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        environment-file: setup/github-actions.yml
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Run tests
      run: |
        python tests/ipytest.py --cov=data_vault -v
    - name: Report coverage
      run: |
        codecov
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint
      run: |
        flake8
